### ISSUE TITLE
Train and Test 

### ISSUE THREAD

**Issue by wbzheng11** [tobiasriedlinger/gradient-metrics-od#1]
Hello, 
I would like to know is there any way to train and test the model ？

**Comment by tobiasriedlinger** [comment]
Hi there, I apologize for the late reply.
Object detection models have their individual training and testing routines which are inherited from the respective source for the most part. Meta classification and meta regression models are trained and evaluated in `uncertainty-aggregation/src/uq.py` after metrics setup has been performed (e.g. for computation of the metadetect features or unpacking gradient features from `.csv`.
