### ISSUE TITLE
model weight

### ISSUE THREAD

**Issue by wbzheng11** [tobiasriedlinger/gradient-metrics-od#2]
Can the author provide the model weight used by faster-rcnn to obtain the gradient metrics( weight_path="/home/riedlinger/OD/faster-rcnn-torch-lfs/weights/coco/retrain/**ckpt_lr_1e-6e+00_ep_3.pt**"), 
thank you!

**Comment by tobiasriedlinger** [comment]
Uploaded the COCO weights to a google drive [here (~500MB)](https://drive.google.com/file/d/1PtRQyUVtDW9j3HWC6D8YhoaxneVUYhKs/view?usp=sharing). Note that gradient computation for the paper results is not parallelized.
Cheers!

**Comment by wbzheng11** [comment]
Ok，I got it .
thanks a lot !

**Comment by wbzheng11** [comment]
Ok，I got it .
thanks a lot !
